export const categoryDescriptions: Record<string, string> = {
  "animals": "Pets, wildlife, and animal-related data APIs",
  "anime": "Anime metadata, ratings, and discovery APIs",
  "anti-malware": "Malware analysis, threat intelligence, and URL reputation",
  "authentication-identity": "Authentication, identity, and authorization providers",
  "books": "Book metadata, libraries, and literature APIs",
  "blockchain-web3": "RPC nodes, on-chain data, and Web3 infrastructure",
  "cryptocurrency": "Cryptocurrency prices, exchanges, and market data",
  "cloud-storage-files": "Object storage, file hosting, and cloud services",
  "development": "Tools and platforms for software development",
  "continuous-integration": "CI/CD pipelines, build tools, and DevOps services",
  "text-analysis-nlp": "NLP, sentiment analysis, and text processing",
  "iot-smart-devices": "Internet of Things and smart device APIs",
  "open-source-projects": "Open source project data and contributor info",
  "dictionaries": "Dictionary, thesaurus, and word definitions",
  "education": "Schools, courses, and educational resources",
  "calendar-holidays": "Holidays, events, and calendar utilities",
  "public-data": "Open datasets across multiple domains",
  "email-sms": "Transactional email, SMS, and messaging delivery",
  "phone-telephony": "Phone numbers, VoIP, and telephony APIs",
  "entertainment": "Movies, TV, trivia, and fun stuff",
  "events": "Concerts, conferences, and event ticketing",
  "podcasts": "Podcast directories, episodes, and RSS feeds",
  "personality-quotes": "Personality tests, quotes, and inspiration",
  "finance": "Payments, banking, stock market, and financial data",
  "currency-exchange": "Forex rates and currency conversion APIs",
  "food-drink": "Recipes, restaurants, nutrition, and cocktail data",
  "games-comics": "Video games, comics, and gaming platforms",
  "geocoding": "Geocoding, mapping, and location services",
  "health": "Medical, fitness, and healthcare APIs",
  "machine-learning": "Machine learning, AI inference, and models",
  "mock-data-testing": "Mock APIs, fake data generators, and testing tools",
  "music": "Streaming, lyrics, and music metadata",
  "news": "Newspapers, headlines, and news aggregation",
  "photography": "Stock photos, image hosting, and visual content",
  "science": "Astronomy, physics, math, and scientific data",
  "security-validation": "Vulnerability scanning, threat intel, and security",
  "data-validation": "Email, phone, and data validation services",
  "shopping": "Products, prices, and ecommerce data",
  "utilities-tools": "Miscellaneous utility and helper APIs",
  "url-shorteners": "URL shorteners and link management",
  "social": "Social networks and community platforms",
  "sports": "Live scores, athletes, and fitness tracking",
  "design-colors": "Design tools, color palettes, and creative APIs",
  "geography-countries": "Country data, flags, and geopolitical info",
  "transportation": "Public transit, flights, vehicles, and routing",
  "tracking-logistics": "Package tracking, shipping, and logistics",
  "environment-climate": "Climate, air quality, and sustainability data",
  "government-civic": "Public sector data and open government APIs",
  "video": "Streaming, video metadata, and processing APIs",
  "math-computation": "Mathematical computation and calculation APIs",
  "unofficial-community": "Unofficial and community-maintained APIs",
  "memes-fun": "Jokes, memes, humor, and fun APIs",
  "jobs-career": "Job listings, career data, and recruiting APIs",
  "weather": "Forecasts, climate, and meteorological data",
  "business": "Business data, registries, and company info",
  "documents-productivity": "Document processing, OCR, and productivity tools",
};
